// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Order struct {
	ID          string   `json:"id"`
	Products    []string `json:"products"`
	TotalAmount float64  `json:"totalAmount"`
	Status      string   `json:"status"`
}

func (Order) IsEntity() {}
