// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Sales struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Code  string `json:"code"`
	Phone string `json:"phone"`
}

func (Sales) IsEntity() {}
